onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_Top_Level/in_ptr
add wave -noupdate /tb_Top_Level/out_ptr
add wave -noupdate /tb_Top_Level/HEADER_BYTES
add wave -noupdate /tb_Top_Level/IMG_WIDTH
add wave -noupdate /tb_Top_Level/IMG_HEIGHT
add wave -noupdate /tb_Top_Level/useless
add wave -noupdate /tb_Top_Level/j
add wave -noupdate /tb_Top_Level/i
add wave -noupdate /tb_Top_Level/k
add wave -noupdate /tb_Top_Level/temp
add wave -noupdate /tb_Top_Level/temp2
add wave -noupdate /tb_Top_Level/write_flag
add wave -noupdate /tb_Top_Level/write_start
add wave -noupdate /tb_Top_Level/prev_haddr
add wave -noupdate /tb_Top_Level/xpadding
add wave -noupdate /tb_Top_Level/ypadding
add wave -noupdate /tb_Top_Level/tb_clk
add wave -noupdate /tb_Top_Level/tb_n_rst
add wave -noupdate /tb_Top_Level/tb_m_hrdata
add wave -noupdate /tb_Top_Level/tb_s_hrdata
add wave -noupdate /tb_Top_Level/tb_m_hready
add wave -noupdate /tb_Top_Level/tb_s_hready
add wave -noupdate /tb_Top_Level/tb_m_haddr
add wave -noupdate /tb_Top_Level/tb_s_haddr
add wave -noupdate /tb_Top_Level/tb_m_hwdata
add wave -noupdate /tb_Top_Level/tb_s_hwdata
add wave -noupdate /tb_Top_Level/tb_m_hwrite
add wave -noupdate /tb_Top_Level/tb_s_hwrite
add wave -noupdate /tb_Top_Level/DUT/clk
add wave -noupdate /tb_Top_Level/DUT/n_rst
add wave -noupdate /tb_Top_Level/DUT/s_haddr
add wave -noupdate /tb_Top_Level/DUT/m_haddr
add wave -noupdate /tb_Top_Level/DUT/m_hrdata
add wave -noupdate /tb_Top_Level/DUT/s_hrdata
add wave -noupdate /tb_Top_Level/DUT/m_hwdata
add wave -noupdate /tb_Top_Level/DUT/s_hwdata
add wave -noupdate /tb_Top_Level/DUT/s_hwrite
add wave -noupdate /tb_Top_Level/DUT/m_hwrite
add wave -noupdate /tb_Top_Level/DUT/s_hready
add wave -noupdate /tb_Top_Level/DUT/m_hready
add wave -noupdate /tb_Top_Level/DUT/re
add wave -noupdate /tb_Top_Level/DUT/we
add wave -noupdate /tb_Top_Level/DUT/read_complete
add wave -noupdate /tb_Top_Level/DUT/write_complete
add wave -noupdate /tb_Top_Level/DUT/buffer2_data
add wave -noupdate /tb_Top_Level/DUT/rgb
add wave -noupdate /tb_Top_Level/DUT/done
add wave -noupdate /tb_Top_Level/DUT/stop
add wave -noupdate /tb_Top_Level/DUT/grayscale_start
add wave -noupdate /tb_Top_Level/DUT/grayscale_data_ready
add wave -noupdate /tb_Top_Level/DUT/gray
add wave -noupdate /tb_Top_Level/DUT/b1_save
add wave -noupdate /tb_Top_Level/DUT/b1_clear
add wave -noupdate /tb_Top_Level/DUT/b1_full
add wave -noupdate /tb_Top_Level/DUT/b1_empty
add wave -noupdate /tb_Top_Level/DUT/m1
add wave -noupdate /tb_Top_Level/DUT/m2
add wave -noupdate /tb_Top_Level/DUT/m3
add wave -noupdate /tb_Top_Level/DUT/m4
add wave -noupdate /tb_Top_Level/DUT/m5
add wave -noupdate /tb_Top_Level/DUT/m6
add wave -noupdate /tb_Top_Level/DUT/m7
add wave -noupdate /tb_Top_Level/DUT/m8
add wave -noupdate /tb_Top_Level/DUT/m9
add wave -noupdate /tb_Top_Level/DUT/m10
add wave -noupdate /tb_Top_Level/DUT/m11
add wave -noupdate /tb_Top_Level/DUT/m12
add wave -noupdate /tb_Top_Level/DUT/m13
add wave -noupdate /tb_Top_Level/DUT/m14
add wave -noupdate /tb_Top_Level/DUT/m15
add wave -noupdate /tb_Top_Level/DUT/m16
add wave -noupdate /tb_Top_Level/DUT/m17
add wave -noupdate /tb_Top_Level/DUT/m18
add wave -noupdate /tb_Top_Level/DUT/m19
add wave -noupdate /tb_Top_Level/DUT/m20
add wave -noupdate /tb_Top_Level/DUT/m21
add wave -noupdate /tb_Top_Level/DUT/m22
add wave -noupdate /tb_Top_Level/DUT/m23
add wave -noupdate /tb_Top_Level/DUT/m24
add wave -noupdate /tb_Top_Level/DUT/m25
add wave -noupdate /tb_Top_Level/DUT/processed_sum_1
add wave -noupdate /tb_Top_Level/DUT/processed_sum_2
add wave -noupdate /tb_Top_Level/DUT/processed_sum_3
add wave -noupdate /tb_Top_Level/DUT/processed_sum_4
add wave -noupdate /tb_Top_Level/DUT/processed_sum_5
add wave -noupdate /tb_Top_Level/DUT/processed_sum_6
add wave -noupdate /tb_Top_Level/DUT/processed_sum_7
add wave -noupdate /tb_Top_Level/DUT/processed_sum_8
add wave -noupdate /tb_Top_Level/DUT/processed_sum_9
add wave -noupdate /tb_Top_Level/DUT/gradient_ready
add wave -noupdate /tb_Top_Level/DUT/gradient_start
add wave -noupdate /tb_Top_Level/DUT/b2_save
add wave -noupdate /tb_Top_Level/DUT/b2_empty
add wave -noupdate /tb_Top_Level/DUT/b2_full
add wave -noupdate /tb_Top_Level/DUT/start_next_write
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
